name: Docker Image Build/Push and Server Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker-build-push:
    name: Docker Image Build/Push
    uses: wibaek/github-automation/.github/workflows/docker-build-push.yaml@v1.0
    with:
      image-name: "ghcr.io/${{ github.repository }}"
      context: "."
      dockerfile: "./Dockerfile"
      platforms: "linux/amd64"
      cache-type: "gha"
      cache-scope: "app"

  ssh-compose-deploy:
    name: SSH Docker Compose Deploy
    needs: docker-build-push
    uses: wibaek/github-automation/.github/workflows/ssh-compose-deploy.yaml@v1.0
    with:
      host: ${{ vars.HOST }}
      port: "22"
      user: ${{ vars.USER }}
      known-hosts: ${{ vars.KNOWN_HOSTS }}
      environment: "prod"
      environment-url: "https://example.com"
      project-directory: "/srv/my-app"
      compose-file: "docker-compose.yml"
      env-file: ".env"
      registry-login: true
      registry: "ghcr.io"
      registry-username: ${{ vars.REGISTRY_USERNAME }}
      image-reference: ${{ needs.docker-build-push.outputs.image-reference }}
      healthcheck-url: "http://127.0.0.1:8000/health"
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
