name: Docker Image Build/Push

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker-build-push:
    name: Docker Image Build/Push
    uses: wibaek/github-automation/.github/workflows/docker-build-push.yaml@v1.2.0
    with:
      image-name: "ghcr.io/${{ github.repository }}"
      context: "."
      dockerfile: "./Dockerfile"
      platforms: "linux/amd64"
      cache-type: "gha"
      cache-scope: "app"
