name: Docker Image Build/Push and Server Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker-build-ghcr-push:
    name: Docker Image Build/Push to GHCR
    permissions:
      contents: read
      packages: write
    uses: wibaek/github-automation/.github/workflows/docker-build-ghcr-push.yaml@v1.0
    with:
      image-name: "ghcr.io/${{ github.repository }}"
      context: "."
      dockerfile: "./Dockerfile"
      platforms: "linux/amd64"
      cache-type: "gha"
      cache-scope: "app"

  ssh-compose-image-load-deploy:
    name: SSH Docker Compose Image Load Deploy
    needs: docker-build-ghcr-push
    permissions:
      contents: read
      packages: read
    uses: wibaek/github-automation/.github/workflows/ssh-compose-image-load-deploy.yaml@v1.0
    with:
      host: ${{ vars.HOST }}
      port: "22"
      user: ${{ vars.USER }}
      known-hosts: ${{ vars.KNOWN_HOSTS }}
      environment: "prod"
      environment-url: "https://example.com"
      project-directory: "/srv/my-app"
      compose-source-file: "docker-compose.yml"
      compose-file: "docker-compose.yml"
      env-file: ".env"
      image-reference: ${{ needs.docker-build-ghcr-push.outputs.image-reference }}
      local-image-name: "my-app"
      service: "app"
      healthcheck-url: "http://127.0.0.1:8000/health"
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
