name: Build

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  node-build:
    name: Node.js Build
    uses: wibaek/github-automation/.github/workflows/node-build.yaml@v1.1.0
    with:
      node-version: "22"
      package-manager: "pnpm"
      pnpm-version: "10"
      lint-command: "auto"
      typecheck-command: "auto"
      test-command: "auto"
      build-command: "auto"
      cache-dependency-path: "pnpm-lock.yaml"
