name: SSH Compose Deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ssh-compose-deploy:
    name: SSH Docker Compose Deploy
    uses: wibaek/github-automation/.github/workflows/ssh-compose-deploy.yaml@v1.0
    with:
      host: ${{ vars.OCI_HOST }}
      port: "22"
      user: ${{ vars.OCI_USER }}
      known-hosts: ${{ vars.OCI_KNOWN_HOSTS }}
      environment: "prod"
      environment-url: "https://example.com"
      project-directory: "/srv/my-app"
      compose-file: "docker-compose.yml"
      env-file: ".env"
      registry-login: true
      registry: "ghcr.io"
      registry-username: ${{ vars.GHCR_USERNAME }}
      image-tag: ${{ github.sha }}
      healthcheck-url: "http://127.0.0.1:8000/health"
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
      REGISTRY_PASSWORD: ${{ secrets.GHCR_READ_TOKEN }}
